sudo: required

language: java
jdk: openjdk8

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
 - chmod +x gradlew

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
  - /home/travis/build/sourceplusplus/Assistant/agent/jvm-agent/build/libs/source-agent-0.2.3.jar
  - /home/travis/build/sourceplusplus/Assistant/api/build/libs/source-api-0.2.3.jar
  - /home/travis/build/sourceplusplus/Assistant/core/build/distributions/source-core-0.2.3.zip
  - /home/travis/build/sourceplusplus/Assistant/plugin/jetbrains-plugin/build/distributions/jetbrains-source-plugin-0.2.3.zip
  - /home/travis/build/sourceplusplus/Assistant/portal/build/distributions/source-portal-0.2.3.zip
  skip_cleanup: true
  on:
    tags: true
