language: java
install: skip

os: linux
dist: xenial
jdk: openjdk11

services:
  - docker

env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

before_install:
 - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
  - /home/travis/build/sourceplusplus/Assistant/api/build/libs/source-api-0.3.1.jar
  - /home/travis/build/sourceplusplus/Assistant/core/build/distributions/source-core-0.3.1.zip
  - /home/travis/build/sourceplusplus/Assistant/plugin/jetbrains-plugin/build/distributions/jetbrains-source-plugin-0.3.1.zip
  - /home/travis/build/sourceplusplus/Assistant/portal/build/distributions/source-portal-0.3.1.zip
  skip_cleanup: true
  on:
    tags: true

after_deploy: 'curl -X POST -v -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/sourceplusplus/assistant/dispatches -d "{\"event_type\":\"publish-release\"}"'
