name: JetBrains Marketplace Auto-Publish

on:
  repository_dispatch:
    types: [publish-release]

jobs:
  compatibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x.x
      - name: Publish the Source++ Assistant plugin to the JetBrains Marketplace
        run: ./gradlew publishPlugin
